name: drails_di
version: 0.0.2
author: Luis Vargas <luisvargastijerino@gmail.com>
description: Drails Dependency Injection Manager
homepage: https://github.com/luisvt/drails_di
environment:
  sdk: '>=1.6.0'
dependencies:
  drails_commons: '>=0.0.1 <0.0.3'
dev_dependencies:
  unittest: '>=0.11.0+5 <0.12.0'
