name: drails_di
version: 0.0.7
author: Luis Vargas <luisvargastijerino@gmail.com>
description: Drails Dependency Injection Manager
homepage: https://github.com/luisvt/drails_di
environment:
  sdk: '>=1.12.0'
dependencies:
  drails_commons: '^0.0.5'
#  drails_commons:
#    path: ../drails_commons
  mockito: '^0.10.1'
dev_dependencies:
  test: any
