name: drails_di
version: 0.3.1
author: Luis Vargas <luisvargastijerino@gmail.com>
description: Drails Dependency Injection Manager
homepage: https://github.com/luisvt/drails_di
environment:
  sdk: '>=2.0.0-dev <3.0.0'
dependencies:
  logging: ^0.11.3
  dson: ^0.13.0
  built_mirrors_core: ^0.8.3
#  dson:
#    path: ../dson
#dependency_overrides:
#  built_mirrors:
#    path: ../built_mirrors
dev_dependencies:
  build_runner: ^0.7.0
  test: ^0.12.19+1
  mockito: ^2.2.0
